services:

  backend:
    build:
      context: ..
      dockerfile: backend/aplications/parser_tg/application/api/Dockerfile
    env_file:
      - ../.env
    ports:
      - 7980:7980
    command: uvicorn --factory backend.aplications.parser_tg.application.api.main:create_app --host 0.0.0.0 --port 7980

  bot:
    build:
      context: ..
      dockerfile: backend/aplications/parser_tg/application/bot/Dockerfile
    env_file:
      - ../.env
    working_dir: /app
    command: python -m backend.aplications.parser_tg.application.bot.main


  scrap_tg:
    build:
      context: ..
      dockerfile: backend/aplications/parser_tg/application/scrapping/Dockerfile
    env_file:
      - ../.env
    volumes:
      - ../backend/aplications/parser_tg:/backend/aplications/parser_tg/
    command: faststream run --factory backend.aplications.parser_tg.application.scrapping.main:main --reload


  writen:
    build:
      context: ..
      dockerfile: backend/aplications/parser_tg/application/writen/Dockerfile
    env_file:
      - ../.env
    command: faststream run --factory backend.aplications.parser_tg.application.writen.main:main

  ner_app:
    build:
      context: ..
      dockerfile: backend/aplications/parser_tg/application/ner_app/Dockerfile
    env_file:
      - ../.env
    command: faststream run --factory backend.aplications.parser_tg.application.ner_app.main:main
